ERROR nova Traceback (most recent call last):
ERROR nova   File "/usr/local/bin/nova-api", line 10, in <module>
ERROR nova     sys.exit(main())
ERROR nova   File "/usr/local/lib/python2.7/dist-packages/nova/cmd/api.py", line 59, in main
ERROR nova     server = service.WSGIService(api, use_ssl=should_use_ssl)
ERROR nova   File "/usr/local/lib/python2.7/dist-packages/nova/service.py", line 311, in __init__
ERROR nova     self.app = self.loader.load_app(name)
ERROR nova   File "/usr/local/lib/python2.7/dist-packages/nova/wsgi.py", line 497, in load_app
...
ERROR nova   File "/usr/local/lib/python2.7/dist-packages/nova/api/openstack/compute/cloudpipe.py", line 55, in setup
ERROR nova     fileutils.ensure_tree(CONF.crypto.keys_path)
ERROR nova   File "/usr/local/lib/python2.7/dist-packages/oslo_utils/fileutils.py", line 40, in ensure_tree
ERROR nova     os.makedirs(path, mode)
ERROR nova   File "/usr/lib/python2.7/os.py", line 157, in makedirs
ERROR nova     mkdir(name, mode)
ERROR nova OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/keys'
